import Test.DocTest

main :: IO ()
main = doctest [ "-XCPP", "-XOverloadedStrings", "-XRankNTypes", "-XLambdaCase"
               , "-ilib"
               -- For the autogenerated Data.GI.CodeGen.GType (hsc)
               , "-idist/build"
               , "dist/build/lib/c/enumStorage.o"
               -- For gobject-introspection
               , "-lgirepository-1.0"
               , "-lgobject-2.0"
               , "-lglib-2.0"
               -- The actual modules to test
               , "Data.GI.GIR.GtkDoc"
               , "Data.GI.CodeGen.ModulePath"
               , "Data.GI.CodeGen.SymbolNaming" ]
