-- Generated code.

{-# LANGUAGE DataKinds, GADTs, KindSignatures, FlexibleInstances #-}

module GI.Signals where

import GHC.TypeLits
import GHC.Exts (Constraint)

class NoConstraint a
instance NoConstraint a

data SignalProxy (a :: Symbol) (b :: Symbol) (c :: * -> Constraint) where
    AccelActivate                        :: SignalProxy "accel-activate" "" NoConstraint
    AccelChanged                         :: SignalProxy "accel-changed" "" NoConstraint
    AccelCleared                         :: SignalProxy "accel-cleared" "" NoConstraint
    AccelClosuresChanged                 :: SignalProxy "accel-closures-changed" "" NoConstraint
    AccelEdited                          :: SignalProxy "accel-edited" "" NoConstraint
    AcceptPosition                       :: SignalProxy "accept-position" "" NoConstraint
    ActionActivated                      :: SignalProxy "action-activated" "" NoConstraint
    ActionsChanged                       :: SignalProxy "actions-changed" "" NoConstraint
    Activate                             :: SignalProxy "activate" "" NoConstraint
    ActivateCurrent                      :: SignalProxy "activate-current" "" NoConstraint
    ActivateCurrentLink                  :: SignalProxy "activate-current-link" "" NoConstraint
    ActivateCursorChild                  :: SignalProxy "activate-cursor-child" "" NoConstraint
    ActivateCursorItem                   :: SignalProxy "activate-cursor-item" "" NoConstraint
    ActivateCursorRow                    :: SignalProxy "activate-cursor-row" "" NoConstraint
    ActivateDefault                      :: SignalProxy "activate-default" "" NoConstraint
    ActivateFocus                        :: SignalProxy "activate-focus" "" NoConstraint
    ActivateItem                         :: SignalProxy "activate-item" "" NoConstraint
    ActivateLink                         :: SignalProxy "activate-link" "" NoConstraint
    Add                                  :: SignalProxy "add" "" NoConstraint
    AddEditable                          :: SignalProxy "add-editable" "" NoConstraint
    AddWidget                            :: SignalProxy "add-widget" "" NoConstraint
    AdjustBounds                         :: SignalProxy "adjust-bounds" "" NoConstraint
    AngleChanged                         :: SignalProxy "angle-changed" "" NoConstraint
    ApplicationActivated                 :: SignalProxy "application-activated" "" NoConstraint
    ApplicationSelected                  :: SignalProxy "application-selected" "" NoConstraint
    Apply                                :: SignalProxy "apply" "" NoConstraint
    ApplyAttributes                      :: SignalProxy "apply-attributes" "" NoConstraint
    ApplyTag                             :: SignalProxy "apply-tag" "" NoConstraint
    AttachWindow                         :: SignalProxy "attach-window" "" NoConstraint
    Backspace                            :: SignalProxy "backspace" "" NoConstraint
    Begin                                :: SignalProxy "begin" "" NoConstraint
    BeginPrint                           :: SignalProxy "begin-print" "" NoConstraint
    BeginUserAction                      :: SignalProxy "begin-user-action" "" NoConstraint
    ButtonPressEvent                     :: SignalProxy "button-press-event" "" NoConstraint
    ButtonReleaseEvent                   :: SignalProxy "button-release-event" "" NoConstraint
    CanActivateAccel                     :: SignalProxy "can-activate-accel" "" NoConstraint
    Cancel                               :: SignalProxy "cancel" "" NoConstraint
    CancelPosition                       :: SignalProxy "cancel-position" "" NoConstraint
    Cancelled                            :: SignalProxy "cancelled" "" NoConstraint
    ChangeCurrentPage                    :: SignalProxy "change-current-page" "" NoConstraint
    ChangeValue                          :: SignalProxy "change-value" "" NoConstraint
    Changed                              :: SignalProxy "changed" "" NoConstraint
    CheckResize                          :: SignalProxy "check-resize" "" NoConstraint
    ChildActivated                       :: SignalProxy "child-activated" "" NoConstraint
    ChildAttached                        :: SignalProxy "child-attached" "" NoConstraint
    ChildDetached                        :: SignalProxy "child-detached" "" NoConstraint
    ChildNotify                          :: SignalProxy "child-notify" "" NoConstraint
    Cleared                              :: SignalProxy "cleared" "" NoConstraint
    Clicked                              :: SignalProxy "clicked" "" NoConstraint
    Close                                :: SignalProxy "close" "" NoConstraint
    CloseWebView                         :: SignalProxy "close-web-view" "" NoConstraint
    CloseWindow                          :: SignalProxy "close-window" "" NoConstraint
    Closed                               :: SignalProxy "closed" "" NoConstraint
    ColorActivated                       :: SignalProxy "color-activated" "" NoConstraint
    ColorChanged                         :: SignalProxy "color-changed" "" NoConstraint
    ColorSet                             :: SignalProxy "color-set" "" NoConstraint
    ColumnsChanged                       :: SignalProxy "columns-changed" "" NoConstraint
    Commit                               :: SignalProxy "commit" "" NoConstraint
    CompositedChanged                    :: SignalProxy "composited-changed" "" NoConstraint
    ConfigureEvent                       :: SignalProxy "configure-event" "" NoConstraint
    ConfirmOverwrite                     :: SignalProxy "confirm-overwrite" "" NoConstraint
    ConnectProxy                         :: SignalProxy "connect-proxy" "" NoConstraint
    ConsoleMessage                       :: SignalProxy "console-message" "" NoConstraint
    ContentLengthReceived                :: SignalProxy "content-length-received" "" NoConstraint
    ContextMenu                          :: SignalProxy "context-menu" "" NoConstraint
    CopyClipboard                        :: SignalProxy "copy-clipboard" "" NoConstraint
    CreateContext                        :: SignalProxy "create-context" "" NoConstraint
    CreateCustomWidget                   :: SignalProxy "create-custom-widget" "" NoConstraint
    CreateMenuProxy                      :: SignalProxy "create-menu-proxy" "" NoConstraint
    CreatePluginWidget                   :: SignalProxy "create-plugin-widget" "" NoConstraint
    CreateWebView                        :: SignalProxy "create-web-view" "" NoConstraint
    CreateWindow                         :: SignalProxy "create-window" "" NoConstraint
    CurrentFolderChanged                 :: SignalProxy "current-folder-changed" "" NoConstraint
    CurrentToplevel                      :: SignalProxy "current-toplevel" "" NoConstraint
    CursorChanged                        :: SignalProxy "cursor-changed" "" NoConstraint
    CursorOnMatch                        :: SignalProxy "cursor-on-match" "" NoConstraint
    CustomItemActivated                  :: SignalProxy "custom-item-activated" "" NoConstraint
    CustomWidgetApply                    :: SignalProxy "custom-widget-apply" "" NoConstraint
    CutClipboard                         :: SignalProxy "cut-clipboard" "" NoConstraint
    CycleChildFocus                      :: SignalProxy "cycle-child-focus" "" NoConstraint
    CycleFocus                           :: SignalProxy "cycle-focus" "" NoConstraint
    CycleHandleFocus                     :: SignalProxy "cycle-handle-focus" "" NoConstraint
    DamageEvent                          :: SignalProxy "damage-event" "" NoConstraint
    DatabaseQuotaExceeded                :: SignalProxy "database-quota-exceeded" "" NoConstraint
    DaySelected                          :: SignalProxy "day-selected" "" NoConstraint
    DaySelectedDoubleClick               :: SignalProxy "day-selected-double-click" "" NoConstraint
    Deactivate                           :: SignalProxy "deactivate" "" NoConstraint
    DeleteEvent                          :: SignalProxy "delete-event" "" NoConstraint
    DeleteFromCursor                     :: SignalProxy "delete-from-cursor" "" NoConstraint
    DeleteRange                          :: SignalProxy "delete-range" "" NoConstraint
    DeleteSurrounding                    :: SignalProxy "delete-surrounding" "" NoConstraint
    DeletedText                          :: SignalProxy "deleted-text" "" NoConstraint
    Deselect                             :: SignalProxy "deselect" "" NoConstraint
    DesktopFolder                        :: SignalProxy "desktop-folder" "" NoConstraint
    Destroy                              :: SignalProxy "destroy" "" NoConstraint
    DestroyEvent                         :: SignalProxy "destroy-event" "" NoConstraint
    DetachWindow                         :: SignalProxy "detach-window" "" NoConstraint
    DirectionChanged                     :: SignalProxy "direction-changed" "" NoConstraint
    DisconnectProxy                      :: SignalProxy "disconnect-proxy" "" NoConstraint
    DocumentLoadFinished                 :: SignalProxy "document-load-finished" "" NoConstraint
    Done                                 :: SignalProxy "done" "" NoConstraint
    DownFolder                           :: SignalProxy "down-folder" "" NoConstraint
    DownloadRequested                    :: SignalProxy "download-requested" "" NoConstraint
    DragActionAsk                        :: SignalProxy "drag-action-ask" "" NoConstraint
    DragActionRequested                  :: SignalProxy "drag-action-requested" "" NoConstraint
    DragBegin                            :: SignalProxy "drag-begin" "" NoConstraint
    DragDataDelete                       :: SignalProxy "drag-data-delete" "" NoConstraint
    DragDataGet                          :: SignalProxy "drag-data-get" "" NoConstraint
    DragDataReceived                     :: SignalProxy "drag-data-received" "" NoConstraint
    DragDrop                             :: SignalProxy "drag-drop" "" NoConstraint
    DragEnd                              :: SignalProxy "drag-end" "" NoConstraint
    DragFailed                           :: SignalProxy "drag-failed" "" NoConstraint
    DragLeave                            :: SignalProxy "drag-leave" "" NoConstraint
    DragMotion                           :: SignalProxy "drag-motion" "" NoConstraint
    DragPerformDrop                      :: SignalProxy "drag-perform-drop" "" NoConstraint
    DragUpdate                           :: SignalProxy "drag-update" "" NoConstraint
    Draw                                 :: SignalProxy "draw" "" NoConstraint
    DrawPage                             :: SignalProxy "draw-page" "" NoConstraint
    EdgeOvershot                         :: SignalProxy "edge-overshot" "" NoConstraint
    EdgeReached                          :: SignalProxy "edge-reached" "" NoConstraint
    Edited                               :: SignalProxy "edited" "" NoConstraint
    EditingBegan                         :: SignalProxy "editing-began" "" NoConstraint
    EditingCanceled                      :: SignalProxy "editing-canceled" "" NoConstraint
    EditingDone                          :: SignalProxy "editing-done" "" NoConstraint
    EditingEnded                         :: SignalProxy "editing-ended" "" NoConstraint
    EditingStarted                       :: SignalProxy "editing-started" "" NoConstraint
    Embedded                             :: SignalProxy "embedded" "" NoConstraint
    EnableDebugging                      :: SignalProxy "enable-debugging" "" NoConstraint
    End                                  :: SignalProxy "end" "" NoConstraint
    EndPrint                             :: SignalProxy "end-print" "" NoConstraint
    EndUserAction                        :: SignalProxy "end-user-action" "" NoConstraint
    Enter                                :: SignalProxy "enter" "" NoConstraint
    EnterNotifyEvent                     :: SignalProxy "enter-notify-event" "" NoConstraint
    EnteringFullscreen                   :: SignalProxy "entering-fullscreen" "" NoConstraint
    Error                                :: SignalProxy "error" "" NoConstraint
    Escape                               :: SignalProxy "escape" "" NoConstraint
    Event                                :: SignalProxy "event" "" NoConstraint
    EventAfter                           :: SignalProxy "event-after" "" NoConstraint
    ExpandCollapseCursorRow              :: SignalProxy "expand-collapse-cursor-row" "" NoConstraint
    ExtendSelection                      :: SignalProxy "extend-selection" "" NoConstraint
    FileActivated                        :: SignalProxy "file-activated" "" NoConstraint
    FileSet                              :: SignalProxy "file-set" "" NoConstraint
    Finished                             :: SignalProxy "finished" "" NoConstraint
    Focus                                :: SignalProxy "focus" "" NoConstraint
    FocusChanged                         :: SignalProxy "focus-changed" "" NoConstraint
    FocusHomeOrEnd                       :: SignalProxy "focus-home-or-end" "" NoConstraint
    FocusInEvent                         :: SignalProxy "focus-in-event" "" NoConstraint
    FocusOutEvent                        :: SignalProxy "focus-out-event" "" NoConstraint
    FocusTab                             :: SignalProxy "focus-tab" "" NoConstraint
    FontActivated                        :: SignalProxy "font-activated" "" NoConstraint
    FontSet                              :: SignalProxy "font-set" "" NoConstraint
    FormatEntryText                      :: SignalProxy "format-entry-text" "" NoConstraint
    FormatValue                          :: SignalProxy "format-value" "" NoConstraint
    FrameCreated                         :: SignalProxy "frame-created" "" NoConstraint
    GeolocationPolicyDecisionCancelled   :: SignalProxy "geolocation-policy-decision-cancelled" "" NoConstraint
    GeolocationPolicyDecisionRequested   :: SignalProxy "geolocation-policy-decision-requested" "" NoConstraint
    GetChildPosition                     :: SignalProxy "get-child-position" "" NoConstraint
    GotPageSize                          :: SignalProxy "got-page-size" "" NoConstraint
    GrabBrokenEvent                      :: SignalProxy "grab-broken-event" "" NoConstraint
    GrabFocus                            :: SignalProxy "grab-focus" "" NoConstraint
    GrabNotify                           :: SignalProxy "grab-notify" "" NoConstraint
    GroupChanged                         :: SignalProxy "group-changed" "" NoConstraint
    Hide                                 :: SignalProxy "hide" "" NoConstraint
    HierarchyChanged                     :: SignalProxy "hierarchy-changed" "" NoConstraint
    HomeFolder                           :: SignalProxy "home-folder" "" NoConstraint
    HoveringOverLink                     :: SignalProxy "hovering-over-link" "" NoConstraint
    IconLoaded                           :: SignalProxy "icon-loaded" "" NoConstraint
    IconPress                            :: SignalProxy "icon-press" "" NoConstraint
    IconRelease                          :: SignalProxy "icon-release" "" NoConstraint
    Input                                :: SignalProxy "input" "" NoConstraint
    InsecureContentRun                   :: SignalProxy "insecure-content-run" "" NoConstraint
    Insert                               :: SignalProxy "insert" "" NoConstraint
    InsertAtCursor                       :: SignalProxy "insert-at-cursor" "" NoConstraint
    InsertChildAnchor                    :: SignalProxy "insert-child-anchor" "" NoConstraint
    InsertPixbuf                         :: SignalProxy "insert-pixbuf" "" NoConstraint
    InsertPrefix                         :: SignalProxy "insert-prefix" "" NoConstraint
    InsertText                           :: SignalProxy "insert-text" "" NoConstraint
    InsertedText                         :: SignalProxy "inserted-text" "" NoConstraint
    InspectWebView                       :: SignalProxy "inspect-web-view" "" NoConstraint
    ItemActivated                        :: SignalProxy "item-activated" "" NoConstraint
    KeyPressEvent                        :: SignalProxy "key-press-event" "" NoConstraint
    KeyReleaseEvent                      :: SignalProxy "key-release-event" "" NoConstraint
    KeynavFailed                         :: SignalProxy "keynav-failed" "" NoConstraint
    KeysChanged                          :: SignalProxy "keys-changed" "" NoConstraint
    Leave                                :: SignalProxy "leave" "" NoConstraint
    LeaveNotifyEvent                     :: SignalProxy "leave-notify-event" "" NoConstraint
    LeavingFullscreen                    :: SignalProxy "leaving-fullscreen" "" NoConstraint
    LoadCommitted                        :: SignalProxy "load-committed" "" NoConstraint
    LoadError                            :: SignalProxy "load-error" "" NoConstraint
    LoadFailed                           :: SignalProxy "load-failed" "" NoConstraint
    LoadFinished                         :: SignalProxy "load-finished" "" NoConstraint
    LoadProgressChanged                  :: SignalProxy "load-progress-changed" "" NoConstraint
    LoadStarted                          :: SignalProxy "load-started" "" NoConstraint
    LocationPopup                        :: SignalProxy "location-popup" "" NoConstraint
    LocationPopupOnPaste                 :: SignalProxy "location-popup-on-paste" "" NoConstraint
    LocationTogglePopup                  :: SignalProxy "location-toggle-popup" "" NoConstraint
    Map                                  :: SignalProxy "map" "" NoConstraint
    MapEvent                             :: SignalProxy "map-event" "" NoConstraint
    MarkDeleted                          :: SignalProxy "mark-deleted" "" NoConstraint
    MarkSet                              :: SignalProxy "mark-set" "" NoConstraint
    MatchSelected                        :: SignalProxy "match-selected" "" NoConstraint
    MimeTypePolicyDecisionRequested      :: SignalProxy "mime-type-policy-decision-requested" "" NoConstraint
    MnemonicActivate                     :: SignalProxy "mnemonic-activate" "" NoConstraint
    ModifiedChanged                      :: SignalProxy "modified-changed" "" NoConstraint
    MonthChanged                         :: SignalProxy "month-changed" "" NoConstraint
    MotionNotifyEvent                    :: SignalProxy "motion-notify-event" "" NoConstraint
    Move                                 :: SignalProxy "move" "" NoConstraint
    MoveActive                           :: SignalProxy "move-active" "" NoConstraint
    MoveCurrent                          :: SignalProxy "move-current" "" NoConstraint
    MoveCursor                           :: SignalProxy "move-cursor" "" NoConstraint
    MoveFocus                            :: SignalProxy "move-focus" "" NoConstraint
    MoveFocusOut                         :: SignalProxy "move-focus-out" "" NoConstraint
    MoveHandle                           :: SignalProxy "move-handle" "" NoConstraint
    MoveScroll                           :: SignalProxy "move-scroll" "" NoConstraint
    MoveSelected                         :: SignalProxy "move-selected" "" NoConstraint
    MoveSlider                           :: SignalProxy "move-slider" "" NoConstraint
    MoveViewport                         :: SignalProxy "move-viewport" "" NoConstraint
    NavigationPolicyDecisionRequested    :: SignalProxy "navigation-policy-decision-requested" "" NoConstraint
    NavigationRequested                  :: SignalProxy "navigation-requested" "" NoConstraint
    NewWindowPolicyDecisionRequested     :: SignalProxy "new-window-policy-decision-requested" "" NoConstraint
    NextMatch                            :: SignalProxy "next-match" "" NoConstraint
    NextMonth                            :: SignalProxy "next-month" "" NoConstraint
    NextYear                             :: SignalProxy "next-year" "" NoConstraint
    NoMatches                            :: SignalProxy "no-matches" "" NoConstraint
    OffsetChanged                        :: SignalProxy "offset-changed" "" NoConstraint
    OnloadEvent                          :: SignalProxy "onload-event" "" NoConstraint
    OpenLocation                         :: SignalProxy "open-location" "" NoConstraint
    OrientationChanged                   :: SignalProxy "orientation-changed" "" NoConstraint
    Output                               :: SignalProxy "output" "" NoConstraint
    OwnerChange                          :: SignalProxy "owner-change" "" NoConstraint
    PageAdded                            :: SignalProxy "page-added" "" NoConstraint
    PageRemoved                          :: SignalProxy "page-removed" "" NoConstraint
    PageReordered                        :: SignalProxy "page-reordered" "" NoConstraint
    Paginate                             :: SignalProxy "paginate" "" NoConstraint
    Pan                                  :: SignalProxy "pan" "" NoConstraint
    ParentSet                            :: SignalProxy "parent-set" "" NoConstraint
    ParsingError                         :: SignalProxy "parsing-error" "" NoConstraint
    PasteClipboard                       :: SignalProxy "paste-clipboard" "" NoConstraint
    PasteDone                            :: SignalProxy "paste-done" "" NoConstraint
    PlugAdded                            :: SignalProxy "plug-added" "" NoConstraint
    PlugRemoved                          :: SignalProxy "plug-removed" "" NoConstraint
    Popdown                              :: SignalProxy "popdown" "" NoConstraint
    PopulatePopup                        :: SignalProxy "populate-popup" "" NoConstraint
    Popup                                :: SignalProxy "popup" "" NoConstraint
    PopupContextMenu                     :: SignalProxy "popup-context-menu" "" NoConstraint
    PopupMenu                            :: SignalProxy "popup-menu" "" NoConstraint
    PostActivate                         :: SignalProxy "post-activate" "" NoConstraint
    PreActivate                          :: SignalProxy "pre-activate" "" NoConstraint
    PreeditChanged                       :: SignalProxy "preedit-changed" "" NoConstraint
    PreeditEnd                           :: SignalProxy "preedit-end" "" NoConstraint
    PreeditStart                         :: SignalProxy "preedit-start" "" NoConstraint
    Prepare                              :: SignalProxy "prepare" "" NoConstraint
    Pressed                              :: SignalProxy "pressed" "" NoConstraint
    PrevMonth                            :: SignalProxy "prev-month" "" NoConstraint
    PrevYear                             :: SignalProxy "prev-year" "" NoConstraint
    Preview                              :: SignalProxy "preview" "" NoConstraint
    PreviousMatch                        :: SignalProxy "previous-match" "" NoConstraint
    PrintRequested                       :: SignalProxy "print-requested" "" NoConstraint
    PropertyNotifyEvent                  :: SignalProxy "property-notify-event" "" NoConstraint
    ProximityInEvent                     :: SignalProxy "proximity-in-event" "" NoConstraint
    ProximityOutEvent                    :: SignalProxy "proximity-out-event" "" NoConstraint
    QueryTooltip                         :: SignalProxy "query-tooltip" "" NoConstraint
    QuickBookmark                        :: SignalProxy "quick-bookmark" "" NoConstraint
    Ready                                :: SignalProxy "ready" "" NoConstraint
    Realize                              :: SignalProxy "realize" "" NoConstraint
    RecentShortcut                       :: SignalProxy "recent-shortcut" "" NoConstraint
    Redo                                 :: SignalProxy "redo" "" NoConstraint
    Released                             :: SignalProxy "released" "" NoConstraint
    Remove                               :: SignalProxy "remove" "" NoConstraint
    RemoveEditable                       :: SignalProxy "remove-editable" "" NoConstraint
    RemoveTag                            :: SignalProxy "remove-tag" "" NoConstraint
    RemoveWidget                         :: SignalProxy "remove-widget" "" NoConstraint
    Render                               :: SignalProxy "render" "" NoConstraint
    ReorderTab                           :: SignalProxy "reorder-tab" "" NoConstraint
    RequestPageSetup                     :: SignalProxy "request-page-setup" "" NoConstraint
    Resize                               :: SignalProxy "resize" "" NoConstraint
    ResourceContentLengthReceived        :: SignalProxy "resource-content-length-received" "" NoConstraint
    ResourceLoadFailed                   :: SignalProxy "resource-load-failed" "" NoConstraint
    ResourceLoadFinished                 :: SignalProxy "resource-load-finished" "" NoConstraint
    ResourceRequestStarting              :: SignalProxy "resource-request-starting" "" NoConstraint
    ResourceResponseReceived             :: SignalProxy "resource-response-received" "" NoConstraint
    Response                             :: SignalProxy "response" "" NoConstraint
    ResponseReceived                     :: SignalProxy "response-received" "" NoConstraint
    RetrieveSurrounding                  :: SignalProxy "retrieve-surrounding" "" NoConstraint
    RowActivated                         :: SignalProxy "row-activated" "" NoConstraint
    RowChanged                           :: SignalProxy "row-changed" "" NoConstraint
    RowCollapsed                         :: SignalProxy "row-collapsed" "" NoConstraint
    RowDeleted                           :: SignalProxy "row-deleted" "" NoConstraint
    RowExpanded                          :: SignalProxy "row-expanded" "" NoConstraint
    RowHasChildToggled                   :: SignalProxy "row-has-child-toggled" "" NoConstraint
    RowInserted                          :: SignalProxy "row-inserted" "" NoConstraint
    RowSelected                          :: SignalProxy "row-selected" "" NoConstraint
    RunFileChooser                       :: SignalProxy "run-file-chooser" "" NoConstraint
    ScaleChanged                         :: SignalProxy "scale-changed" "" NoConstraint
    ScreenChanged                        :: SignalProxy "screen-changed" "" NoConstraint
    ScriptAlert                          :: SignalProxy "script-alert" "" NoConstraint
    ScriptConfirm                        :: SignalProxy "script-confirm" "" NoConstraint
    ScriptPrompt                         :: SignalProxy "script-prompt" "" NoConstraint
    ScrollChild                          :: SignalProxy "scroll-child" "" NoConstraint
    ScrollEvent                          :: SignalProxy "scroll-event" "" NoConstraint
    ScrollbarsPolicyChanged              :: SignalProxy "scrollbars-policy-changed" "" NoConstraint
    SearchChanged                        :: SignalProxy "search-changed" "" NoConstraint
    SearchShortcut                       :: SignalProxy "search-shortcut" "" NoConstraint
    Select                               :: SignalProxy "select" "" NoConstraint
    SelectAll                            :: SignalProxy "select-all" "" NoConstraint
    SelectCursorItem                     :: SignalProxy "select-cursor-item" "" NoConstraint
    SelectCursorParent                   :: SignalProxy "select-cursor-parent" "" NoConstraint
    SelectCursorRow                      :: SignalProxy "select-cursor-row" "" NoConstraint
    SelectPage                           :: SignalProxy "select-page" "" NoConstraint
    SelectedChildrenChanged              :: SignalProxy "selected-children-changed" "" NoConstraint
    SelectedRowsChanged                  :: SignalProxy "selected-rows-changed" "" NoConstraint
    SelectionChanged                     :: SignalProxy "selection-changed" "" NoConstraint
    SelectionClearEvent                  :: SignalProxy "selection-clear-event" "" NoConstraint
    SelectionDone                        :: SignalProxy "selection-done" "" NoConstraint
    SelectionGet                         :: SignalProxy "selection-get" "" NoConstraint
    SelectionNotifyEvent                 :: SignalProxy "selection-notify-event" "" NoConstraint
    SelectionReceived                    :: SignalProxy "selection-received" "" NoConstraint
    SelectionRequestEvent                :: SignalProxy "selection-request-event" "" NoConstraint
    SequenceStateChanged                 :: SignalProxy "sequence-state-changed" "" NoConstraint
    SetAnchor                            :: SignalProxy "set-anchor" "" NoConstraint
    SetFocus                             :: SignalProxy "set-focus" "" NoConstraint
    SetFocusChild                        :: SignalProxy "set-focus-child" "" NoConstraint
    ShouldApplyStyle                     :: SignalProxy "should-apply-style" "" NoConstraint
    ShouldBeginEditing                   :: SignalProxy "should-begin-editing" "" NoConstraint
    ShouldChangeSelectedRange            :: SignalProxy "should-change-selected-range" "" NoConstraint
    ShouldDeleteRange                    :: SignalProxy "should-delete-range" "" NoConstraint
    ShouldEndEditing                     :: SignalProxy "should-end-editing" "" NoConstraint
    ShouldInsertNode                     :: SignalProxy "should-insert-node" "" NoConstraint
    ShouldInsertText                     :: SignalProxy "should-insert-text" "" NoConstraint
    ShouldShowDeleteInterfaceForElement  :: SignalProxy "should-show-delete-interface-for-element" "" NoConstraint
    Show                                 :: SignalProxy "show" "" NoConstraint
    ShowConnectToServer                  :: SignalProxy "show-connect-to-server" "" NoConstraint
    ShowEnterLocation                    :: SignalProxy "show-enter-location" "" NoConstraint
    ShowErrorMessage                     :: SignalProxy "show-error-message" "" NoConstraint
    ShowHelp                             :: SignalProxy "show-help" "" NoConstraint
    ShowHidden                           :: SignalProxy "show-hidden" "" NoConstraint
    ShowMenu                             :: SignalProxy "show-menu" "" NoConstraint
    ShowWindow                           :: SignalProxy "show-window" "" NoConstraint
    SizeAllocate                         :: SignalProxy "size-allocate" "" NoConstraint
    SizeChanged                          :: SignalProxy "size-changed" "" NoConstraint
    SortColumnChanged                    :: SignalProxy "sort-column-changed" "" NoConstraint
    StartInteractiveSearch               :: SignalProxy "start-interactive-search" "" NoConstraint
    StateChanged                         :: SignalProxy "state-changed" "" NoConstraint
    StateFlagsChanged                    :: SignalProxy "state-flags-changed" "" NoConstraint
    StateSet                             :: SignalProxy "state-set" "" NoConstraint
    StatusBarTextChanged                 :: SignalProxy "status-bar-text-changed" "" NoConstraint
    StatusChanged                        :: SignalProxy "status-changed" "" NoConstraint
    StopSearch                           :: SignalProxy "stop-search" "" NoConstraint
    Stopped                              :: SignalProxy "stopped" "" NoConstraint
    StyleChanged                         :: SignalProxy "style-changed" "" NoConstraint
    StyleSet                             :: SignalProxy "style-set" "" NoConstraint
    StyleUpdated                         :: SignalProxy "style-updated" "" NoConstraint
    Swipe                                :: SignalProxy "swipe" "" NoConstraint
    SwitchPage                           :: SignalProxy "switch-page" "" NoConstraint
    TagAdded                             :: SignalProxy "tag-added" "" NoConstraint
    TagChanged                           :: SignalProxy "tag-changed" "" NoConstraint
    TagRemoved                           :: SignalProxy "tag-removed" "" NoConstraint
    TestCollapseRow                      :: SignalProxy "test-collapse-row" "" NoConstraint
    TestExpandRow                        :: SignalProxy "test-expand-row" "" NoConstraint
    TextPopped                           :: SignalProxy "text-popped" "" NoConstraint
    TextPushed                           :: SignalProxy "text-pushed" "" NoConstraint
    TitleChanged                         :: SignalProxy "title-changed" "" NoConstraint
    ToggleCursorChild                    :: SignalProxy "toggle-cursor-child" "" NoConstraint
    ToggleCursorItem                     :: SignalProxy "toggle-cursor-item" "" NoConstraint
    ToggleCursorRow                      :: SignalProxy "toggle-cursor-row" "" NoConstraint
    ToggleCursorVisible                  :: SignalProxy "toggle-cursor-visible" "" NoConstraint
    ToggleHandleFocus                    :: SignalProxy "toggle-handle-focus" "" NoConstraint
    ToggleOverwrite                      :: SignalProxy "toggle-overwrite" "" NoConstraint
    ToggleSizeAllocate                   :: SignalProxy "toggle-size-allocate" "" NoConstraint
    ToggleSizeRequest                    :: SignalProxy "toggle-size-request" "" NoConstraint
    Toggled                              :: SignalProxy "toggled" "" NoConstraint
    ToolbarReconfigured                  :: SignalProxy "toolbar-reconfigured" "" NoConstraint
    TouchEvent                           :: SignalProxy "touch-event" "" NoConstraint
    Undo                                 :: SignalProxy "undo" "" NoConstraint
    Unmap                                :: SignalProxy "unmap" "" NoConstraint
    UnmapEvent                           :: SignalProxy "unmap-event" "" NoConstraint
    Unrealize                            :: SignalProxy "unrealize" "" NoConstraint
    UnselectAll                          :: SignalProxy "unselect-all" "" NoConstraint
    UpFolder                             :: SignalProxy "up-folder" "" NoConstraint
    Update                               :: SignalProxy "update" "" NoConstraint
    UpdateCustomWidget                   :: SignalProxy "update-custom-widget" "" NoConstraint
    UpdatePreview                        :: SignalProxy "update-preview" "" NoConstraint
    UserChangedContents                  :: SignalProxy "user-changed-contents" "" NoConstraint
    ValueChanged                         :: SignalProxy "value-changed" "" NoConstraint
    ViewportAttributesChanged            :: SignalProxy "viewport-attributes-changed" "" NoConstraint
    ViewportAttributesRecomputeRequested :: SignalProxy "viewport-attributes-recompute-requested" "" NoConstraint
    VisibilityNotifyEvent                :: SignalProxy "visibility-notify-event" "" NoConstraint
    WebViewReady                         :: SignalProxy "web-view-ready" "" NoConstraint
    WindowAdded                          :: SignalProxy "window-added" "" NoConstraint
    WindowObjectCleared                  :: SignalProxy "window-object-cleared" "" NoConstraint
    WindowRemoved                        :: SignalProxy "window-removed" "" NoConstraint
    WindowStateEvent                     :: SignalProxy "window-state-event" "" NoConstraint
    Wrapped                              :: SignalProxy "wrapped" "" NoConstraint
